export declare function helloYamaCore(): string;
export { SchemaValidator, createSchemaValidator, schemaToJsonSchema, fieldToJsonSchema, type SchemaField, type SchemaDefinition, type YamaSchemas, type ValidationResult } from "./schemas";
export { type AuthProvider, type AuthConfig, type EndpointAuth, type AuthContext, type AuthProviderType, type JwtAuthProvider, type ApiKeyAuthProvider, } from "./schemas";
export { authenticateRequest, authorizeRequest, authenticateAndAuthorize, } from "./auth";
export { generateTypes } from "./typegen";
export { type EntityField, type EntityFieldType, type EntityDefinition, type EntityIndex, type YamaEntities, type DatabaseConfig, entityToSchema, entitiesToSchemas, mergeSchemas, } from "./entities";
export { loadEnvFile, resolveEnvVar, resolveEnvVars, } from "./env";
export { type DatabaseAdapter, type DatabaseConnection, createDatabaseAdapter, registerDatabaseAdapter, } from "./infrastructure/database";
export { type HttpServerAdapter, type HttpRequest, type HttpResponse, type RouteHandler, type HttpServerInstance, createHttpServerAdapter, registerHttpServerAdapter, } from "./infrastructure/server";
export { type ServerConfig, } from "./entities";
export { type PluginManifest, type YamaPlugin, type ServicePlugin, type PluginContext, loadPlugin, getPlugin, getAllPlugins, getPluginByCategory, getPluginsByCategory, getPluginByType, loadPluginFromPackage, loadServicePlugin, getServicePlugin, getServicePluginByType, } from "./plugins/index";
export { type Model, type TableModel, type ColumnModel, type IndexModel, type ForeignKeyModel, type MigrationDiff, computeModelHash, entitiesToModel, compareModels, } from "./migrations/model";
export { type DiffResult, type MigrationStepType, type MigrationStep, type AddTableStep, type DropTableStep, type AddColumnStep, type DropColumnStep, type ModifyColumnStep, type AddIndexStep, type DropIndexStep, type AddForeignKeyStep, type DropForeignKeyStep, type MigrationStepUnion, computeDiff, diffToSteps, } from "./migrations/diff";
export { type MigrationYAML, serializeMigration, deserializeMigration, createMigration, } from "./migrations/migration-yaml";
export { type ValidationError, validateMigrationYAML, validateMigrationHash, validateStepDependencies, validateMigration, } from "./migrations/validator";
export { replayMigrations, getCurrentModelHashFromDB, } from "./migrations/replay";
export { type TrashEntry, type TrashStatus, DEFAULT_RETENTION_DAYS, calculateExpirationDate, isExpired, } from "./migrations/trash";
