/**
 * Repository loading utilities for YAMA Node Runtime
 * 
 * This module handles loading of entity repositories from generated database code.
 * Repositories provide type-safe database operations for entities.
 */

import { existsSync } from "fs";
import { join, resolve } from "path";
import { pathToFileURL } from "url";
import type { YamaEntities } from "@betagors/yama-core";

/**
 * Load entity repositories from generated database code
 * 
 * Maps entity names to repository instances (e.g., "Product" → productRepository).
 * Repositories are generated by `yama generate` command and provide type-safe
 * database operations like findAll, findById, create, update, delete.
 * 
 * @param configDir - Directory containing yama.yaml configuration
 * @param entities - Entity definitions from configuration
 * @returns Map of entity names to repository instances
 * 
 * @remarks
 * - Returns empty object if no entities are defined
 * - Warns if repository files don't exist (requires `yama generate`)
 * - Returns empty object on error (runtime continues without repositories)
 * 
 * @example
 * ```typescript
 * const repositories = await loadRepositories("/path/to/project", config.entities);
 * // repositories = { Product: productRepository, User: userRepository, ... }
 * 
 * // Use in handler context:
 * context.entities.Product.findAll({ limit: 10 });
 * ```
 */
export async function loadRepositories(
  configDir: string,
  entities?: YamaEntities
): Promise<Record<string, unknown>> {
  const repositories: Record<string, unknown> = {};

  // If no entities defined, return empty object
  if (!entities || Object.keys(entities).length === 0) {
    return repositories;
  }

  // Construct path to .yama/gen/db/index.ts
  const dbIndexPath = join(configDir, ".yama", "gen", "db", "index.ts");

  // Check if repository index file exists
  if (!existsSync(dbIndexPath)) {
    console.warn(`⚠️  Repository index not found: ${dbIndexPath}`);
    console.warn(`   Run 'yama generate' to generate database repositories.`);
    console.warn(`   Handlers using context.entities.* will fail until repositories are generated.`);
    return repositories;
  }

  try {
    // Convert to absolute path and then to file URL for ES module import
    const absolutePath = resolve(dbIndexPath);
    const fileUrl = pathToFileURL(absolutePath).href;

    // Dynamic import for ES modules
    const repositoryModule = await import(fileUrl);

    // Map entity names to repository instances
    // Entity "Product" → repository export "productRepository"
    for (const entityName of Object.keys(entities)) {
      const repositoryName = `${entityName.charAt(0).toLowerCase() + entityName.slice(1)}Repository`;
      
      if (repositoryName in repositoryModule) {
        repositories[entityName] = repositoryModule[repositoryName];
        console.log(`✅ Loaded repository: ${entityName} → ${repositoryName}`);
      } else {
        console.warn(`⚠️  Repository ${repositoryName} not found for entity ${entityName}`);
      }
    }
  } catch (error) {
    console.warn(
      `⚠️  Failed to load repositories from ${dbIndexPath}:`,
      error instanceof Error ? error.message : String(error)
    );
    // Return empty object on error - runtime continues without repositories
  }

  return repositories;
}
